/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Controlador.AnalizadorLexico;
import util.FlujoCaracteres;
import util.Lexema;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manuel Alejandro
 */
public class VentanaPrincipal extends javax.swing.JFrame {

  /**
   * Creates new form VentanaPrincipal
   */
  public VentanaPrincipal() {

    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnAnalizar = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTAPalabras = new javax.swing.JTextArea();
    jScrollPane3 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    btnAnalizar.setText("Analizar");
    btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAnalizarActionPerformed(evt);
      }
    });

    jTAPalabras.setColumns(20);
    jTAPalabras.setRows(5);
    jScrollPane2.setViewportView(jTAPalabras);

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][] { { null, null }, { null, null }, { null, null }, { null, null } },
        new String[] { "Token", "Tipo" }));
    jScrollPane3.setViewportView(jTable1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup().addGap(20, 20, 20)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(btnAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 349,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 426,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 324,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(120, 120, 120)))));
    layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
        .createSequentialGroup().addContainerGap().addComponent(btnAnalizar).addGap(11, 11,
            11)
        .addGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane2)
                .addGroup(
                    layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 265,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 191, Short.MAX_VALUE)))
        .addContainerGap()));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAnalizarActionPerformed
    // TODO add your handling code here:
    String cadena = "";
    AnalizadorLexico.listLexema.removeAll(AnalizadorLexico.listLexema);

    char[] caracteres;
    if (jTAPalabras.getText().equals("")) {

    } else {
      String chat = "";
      cadena = jTAPalabras.getText();
      String[] lineas = cadena.split("\n");
      System.out.println(lineas);
      for (int i = 0; i < lineas.length; i++) {
        chat = chat + " " + lineas[i];

      }
      caracteres = chat.toCharArray();
      FlujoCaracteres ca = new FlujoCaracteres(0, caracteres);
      AnalizadorLexico al = new AnalizadorLexico();
      al.analizar(ca);
      tablaLexemas();
    }

//            for (int i = 0; i < al.getListLexema().size(); i++) {
//
//                
//                    txtMostrar.setText(" Token" + " - " + al.getListLexema().get(i).getToken()
//                            + "\n Tipo" + " - " + al.getListLexema().get(i).getTipoLexema());
//                
//            
//            }

  }// GEN-LAST:event_btnAnalizarActionPerformed

  public void tablaLexemas() {
    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("Token");
    model.addColumn("Tipo Lexema");

    for (int i = 0; i < AnalizadorLexico.listLexema.size(); i++) {
      model.addRow(new Object[] { (i + 1), AnalizadorLexico.listLexema.get(i).getToken(),
          AnalizadorLexico.listLexema.get(i).getTipoLexema()

      });
    }

    jTable1.setModel(model);
  }

  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
          ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
          ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
          ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
          ex);
    }
    // </editor-fold>
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VentanaPrincipal().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAnalizar;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JTextArea jTAPalabras;
  private javax.swing.JTable jTable1;
  // End of variables declaration//GEN-END:variables
}
